### ISSUE TITLE
Fix gateway mapping makes undefined reference to key 1349 FTIME

### ISSUE THREAD

**Issue by Maker42** [birkelbach/python-canfix#11]
But that key is not present in canfix.xml

**Comment by birkelbach** [comment]
python-canfix doesn't care about those keys.  I don't understand what problem you are having.

**Comment by Maker42** [comment]
FIX-Gatway/config/canfix/map.yaml refers to FTIME, key 1349.

The Fix gateway mapping depends on all the mapped keys to be present in canfix.xml, but key 1349 is not.

**Comment by Maker42** [comment]
So the problem shows up in FIX-Gateway, but the root cause is in python-canfix.

**Comment by birkelbach** [comment]
The canfix plugin doesn't care about the key (i.e. FTIME) it only cares about the parameter number (i.e. 1349)  That parameter is in the json file for the python-canfix package.  I think you have an old version of the python-canfix package since it was converted to use json about three months ago.  Try the latest version and see if that works.

**Comment by Maker42** [comment]
You're right. My python-canfix was checked out on a branch, and all git said was "HEAD" which I ASSumed was master. Eveything's good now.
